#!/usr/bin/env bash

if
  [[ -s "/home/aniss/.rvm/gems/ruby-1.9.3-p547@global/environment" ]]
then
  source "/home/aniss/.rvm/gems/ruby-1.9.3-p547@global/environment"
  exec gem "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/aniss/.rvm/gems/ruby-1.9.3-p547@global/environment'" >&2
  exit 1
fi
